version: "2"

services:
  nginx.symfony:
    container_name: nginx.symfony
    build: nginx
    volumes:
      - ./examples:/code # Mount your code, so nginx/phpcould see it
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf # Use custom virtual hosts
    ports:
      - 127.0.0.1:8000:8000 # For development. Open in browser 127.0.0.1:8000

  php.symfony:
    container_name: php.symfony
    build: php
    volumes:
      - ./examples:/code # Mount your code, so nginx/phpcould see it

  mysql.symfony:
    container_name: mysql.symfony
    build: mysql
    volumes:
      - .docker/mysql-data/:/var/lib/mysql # To persist data between restarts
    ports:
      - 127.0.0.1:3307:3306 # Connect to it via -h127.0.0.1 --port=3307

  frontend.symfony:
    build: frontend/
    container_name: frontend.symfony
    volumes:
      - ./examples:/code # Mount your code, so javaScript tools could see it