version: "2"

services:
  frontend.symfony:
    build: frontend/
    container_name: frontend.symfony
    volumes:
      - ./examples:/code # Mount your code, so javaScript tools could see it

  ide.symfony:
    build: ide
    container_name: ide.symfony
    environment:
      DISPLAY: $DISPLAY
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./examples:/code
      - ./.docker/ide-home:/home/developer # Ensure directory is writable, otherwise there will be code.path errors from PHPStorm
    ports:
      - 127.0.0.1:9000:9000
    entrypoint: "/ide/bin/phpstorm.sh"
